// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('testfilenodb', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('testfilenodb', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1440, height: 900 })
    await driver.findElement(By.linkText("Add")).click()
    assert(await driver.findElement(By.css(".form-group:nth-child(1) > label")).getText() == "Title")
  })
})
